import { Interface } from '@ethersproject/abi'
import STACKING_TICKETS_ABI from './staking_tickets.json'
import STACKING_TICKETS_ABI_V2 from './staking_tickets_v2.json'

const STACKING_TICKETS_INTERFACE = new Interface(STACKING_TICKETS_ABI)
const STACKING_TICKETS_INTERFACE_V2 = new Interface(STACKING_TICKETS_ABI_V2)

//export default {STACKING_TICKETS_INTERFACE, STACKING_TICKETS_ABI, STACKING_TICKETS_INTERFACE_V2, STACKING_TICKETS_ABI_V2 }
export { STACKING_TICKETS_INTERFACE }
export { STACKING_TICKETS_ABI }
export {STACKING_TICKETS_INTERFACE_V2}
export {STACKING_TICKETS_ABI_V2 }

